version: 0.2

env:
  shell: bash
  variables:
    SPRING_PROFILES_ACTIVE: "dev"
    ALADIN_TTB_KEY: ""

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo starting build stage
      - cd backend
      - mvn package
  post_build:
    commands:
      - pwd
artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
