spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    pretty-print: true
    deserialization:
      fail-on-unknown-properties: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
aladin-ttb-key: ${ALADIN_TTB_KEY}
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      note-image-bucket: ${AWS_S3_NOTE_IMAGE_BUCKET}

---
spring:
  profiles: dev
spring-jwt-secret: ${JWT_SECRET}

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
spring-jwt-secret: kFw_ghm_8xA76Y9c0fBuZMvcMs4Hw4SBS6tJyASQd4PcPeXRyHDKrf-198eXzLlYEeYxw0Es5WaVVMF8_ofQkA
cloud:
  aws:
    credentials:
      access-key: AKIAIOSFODNN7EXAMPLE
      secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    region:
      static: ap-northeast-2
    s3:
      endpoint-uri: http://localhost:9090
      note-image-bucket: notes

---
spring:
  profiles: dev-local
  datasource:
    # Run local postgresql server with:
    # docker run -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=pass -e POSTGRES_DB=openbook -d postgres
    url: jdbc:postgresql://localhost:5432/openbook
    username: postgres
    password: pass
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
spring-jwt-secret: kFw_ghm_8xA76Y9c0fBuZMvcMs4Hw4SBS6tJyASQd4PcPeXRyHDKrf-198eXzLlYEeYxw0Es5WaVVMF8_ofQkA
